# Generated by Django 5.0.2 on 2024-03-05 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('total_dose', models.IntegerField(blank=True, null=True)),
                ('dose', models.IntegerField()),
                ('price', models.IntegerField()),
                ('is_complete_dose', models.BooleanField(default=False)),
                ('next_dose', models.DateField(blank=True, null=True)),
                ('description', models.TextField(max_length=600)),
                ('image', models.ImageField(upload_to='vaccine/upload/images/')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='account.account')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='vaccine.vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine_Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasReviewed', models.BooleanField(default=False)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='account.account')),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='vaccine.schedule')),
                ('vaccine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='vaccine.vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.CharField(choices=[('⭐', '⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')], max_length=10)),
                ('review', models.TextField()),
                ('vaccine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccine.vaccine')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='vaccine.vaccine_recipient')),
            ],
        ),
    ]
