# Generated by Django 5.0 on 2024-03-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='description',
            field=models.TextField(max_length=600),
        ),
    ]
