# Generated by Django 5.0 on 2024-03-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine_recipient',
            name='taken_dose',
            field=models.IntegerField(default=0),
        ),
    ]
