# Generated by Django 5.0 on 2024-03-11 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0004_remove_vaccine_is_complete_dose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine_recipient',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='vaccine.schedule'),
        ),
    ]
